### ISSUE TITLE
bug: application_owners is always the current user

### ISSUE THREAD

**Issue by lra** [lacework/terraform-azure-ad-application#39]
**Describe the bug**

When no `application_owners` are specified, the terraform code assume the owner of the azuread_application is always `data.azuread_client_config.current.object_id`.

This works if the user doing `terraform plan` is the same as the one who did create the azuread_application (by doing a `terraform apply`).

But if another user does a terraform plan, it will show a drift about `azuread_application.owners` . Worse if another user tries to apply the same resource as terraform will try to change the owner.

Not sure what's the best way to solve this, but the module should not expect a different `azuread_application.owners` depending on who's doing a terraform plan/apply.

**Steps to reproduce**

1. Terraform apply without specifying `application_owners`
2. Terraform plan with another user

**Expected behavior**

There should be no drift.

**Screenshots**

It will show a drift like:
```
Terraform will perform the following actions:

  # module.az_ad_application.azuread_application.lacework[0] will be updated in-place
  ~ resource "azuread_application" "lacework" {
        id                             = "SOME_ID"
      ~ owners                         = [
          + "ID_OF_USER_PLANNING",
          - "ID_OF_ORIGINAL_USER_THAT_CREATED_THE_APP",
        ]
        tags                           = []
        # (17 unchanged attributes hidden)






        # (6 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Please complete the following information):**
```
Terraform v1.2.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/lacework/lacework v0.19.0
```

**Comment by afiune** [comment]
@lra one option I am seeing for you to solve this drift issue is to try defining the input `application_owners`? 

Would this work for you?

**Comment by lra** [comment]
Yes, that's the workaround we are using. But for the provider, `azuread_application.owners` is optional, so you should just set it to null if the module user does not state it, instead of guessing it dynamically.

**Comment by marcosgm** [comment]
Thanks for the feedback! We decided to guess it dynamically so the App would show up as the first result in the App Registrations page in the Portal, for the user that is executing Terraform from the cloud shell, which is our preferred onboarding way. This has helped a lot, especially with users new to Terraform.
We trust advanced users (i.e. Terraform Cloud) to read all the variables description, if they are default or not, and what it implies.
In this case, the documentation for that variable reads: _The owners of the Azure Active Directory Application. If empty, current user will be owner_
You can also choose to not use this module, and instead take the Config and Activity Log modules and point them to a principal created elsewhere (this is especially interesting if your Azure AD is managed by a different team and you don't have User Administrator rights in Azure AD).

**Comment by lra** [comment]
I don't get why you'd rather have a changing value for something that's supposed to be static, rather than to set it to null.
