### ISSUE TITLE
feat: Cannot use azuread v3

### ISSUE THREAD

**Issue by lra** [lacework/terraform-azure-ad-application#58]
We can't use the module with azuread v3+ released recently: https://github.com/hashicorp/terraform-provider-azuread/releases
It's blocked by https://github.com/lacework/terraform-azure-ad-application/blob/main/versions.tf#L7

**Comment by leijin-lw** [comment]
Support for azureAD v3 has been added in new version 2.X

**Comment by lra** [comment]
Thanks!
